# -*- coding: utf-8 -*-
"""Untitled28.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h9TUNlgyX8m50ihzA5--orlY5nsjGQsA
"""

#Name SHARATH KUMAR.M
#Creation date- 07/04/2021
#version - Python3.6
#Objective of this script is to display title of books from first n pages and where rating = x , where x and n are user defined




#importing all the required libraries
import requests
import bs4

#taking user input
while 1:
  n=input('Enter Number of pages to be check, number should be greater then 1 and less then 50\n')
  try:
    n=int(n)
  except:
    print('Please Enter digit!!!!')
    continue
  if(n<1 or n>50):
    print('Number should be greater then 1 and less then 50, enter again')
    continue
  break
while 1:
  x=input('Enter Rating\n')
  try:
    x=int(x)
  except:
    print('Please Enter digit between 1-5!!!!')
    continue
  if(x<1 or x>5):
    print('Rating can be only between 1-5, retry')
    continue
  break


# defining selector according to user input.
if(x==1):
  selector='star-rating.One'
elif(x==2):
  selector='.star-rating.Two'
elif(x==3):
  selector='.star-rating.Three'
elif(x==4):
  selector='.star-rating.Four'
elif(x==5):
  selector='.star-rating.Five'
base_url = 'http://books.toscrape.com/catalogue/page-{}.html'
titles = []
# Now iterate to get info from each page.
# We want to include page 5, so index should go up to, but not include 6,
for page in range (n):
  scrape_url = base_url.format(page+1)
  res = requests.get(scrape_url)
  soup = bs4.BeautifulSoup(res.text,'lxml')
  books = soup.select(".product_pod")
  # within our loop, we'll create another loop to parse the books that have rating x.
  for book in books:
    if len(book.select(selector)) != 0: 
      book_title = book.select('a')[1]['title']
      titles.append(book_title)

print("All the books in first "+str(n) +" pages whose rating is "+str(x)+" are follows")
for tit in titles:
	print(tit)